// Import Material Design themes
import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

const lightColors = {
  ...MD3LightTheme.colors,
  primary: "#6EC1E4",                // Vibrant sky blue
  onPrimary: "#FFFFFF",
  primaryContainer: "#B3EAF6",       // Lighter blue tint
  onPrimaryContainer: "#003E50",
  secondary: "#2E8B57",              // Deep forest green
  onSecondary: "#FFFFFF",
  secondaryContainer: "#A5D6A7",       // Soft green tint
  onSecondaryContainer: "#004D40",
  tertiary: "#CDA135",               // Warm earthy gold
  onTertiary: "#1D1400",
  tertiaryContainer: "#FFF7D9",      // Creamy tint
  onTertiaryContainer: "#3B2F00",
  error: "#BA1A1A",
  onError: "#FFFFFF",
  errorContainer: "#FFDAD6",
  onErrorContainer: "#93000A",
  background: "#F6FAFC",
  onBackground: "#171C1E",
  surface: "#FFFFFF",
  onSurface: "#171C1E",
  surfaceVariant: "#D9E4E9",
  onSurfaceVariant: "#3E484D",
  outline: "#6E797D",
  outlineVariant: "#BDC8CD",
  shadow: "#000000",
  scrim: "#000000",
  inverseSurface: "#2C3133",
  inverseOnSurface: "#EDF1F4",
  inversePrimary: "#5C97B1",
  primaryFixed: "#B3EAF6",
  onPrimaryFixed: "#001F27",
  primaryFixedDim: "#68D4F5",
  onPrimaryFixedVariant: "#004E5F",
  secondaryFixed: "#80BDB8",
  onSecondaryFixed: "#00251A",
  secondaryFixedDim: "#4DB6AC",
  onSecondaryFixedVariant: "#004D40",
  tertiaryFixed: "#FFF7D9",
  onTertiaryFixed: "#2A2000",
  tertiaryFixedDim: "#F2D878",
  onTertiaryFixedVariant: "#584A00",
  surfaceDim: "#D6DBDD",
  surfaceBright: "#FFFFFF",
  surfaceContainerLowest: "#FFFFFF",
  surfaceContainerLow: "#F0F4F7",
  surfaceContainer: "#EAEEF1",
  surfaceContainerHigh: "#E4E9EB",
  surfaceContainerHighest: "#DFE3E6",
};

const darkColors = {
  ...MD3DarkTheme.colors,
  primary: "#6EC1E4",
  onPrimary: "#003B4C",
  primaryContainer: "#005C80",
  onPrimaryContainer: "#B3EAF6",
  secondary: "#4A9A90",              // Darker version of the green
  onSecondary: "#00251A",
  secondaryContainer: "#004F55",
  onSecondaryContainer: "#B2DFDB",
  tertiary: "#BDA82B",               // Muted warm gold
  onTertiary: "#3B2F00",
  tertiaryContainer: "#3E2F00",
  onTertiaryContainer: "#FFF7D9",
  error: "#FFB4AB",
  onError: "#690005",
  errorContainer: "#93000A",
  onErrorContainer: "#FFDAD6",
  background: "#0F1416",
  onBackground: "#DFE3E6",
  surface: "#0F1416",
  onSurface: "#DFE3E6",
  surfaceVariant: "#3E484D",
  onSurfaceVariant: "#BDC8CD",
  outline: "#879397",
  outlineVariant: "#3E484D",
  shadow: "#000000",
  scrim: "#000000",
  inverseSurface: "#DFE3E6",
  inverseOnSurface: "#2C3133",
  inversePrimary: "#5C97B1",
  primaryFixed: "#B3EAF6",
  onPrimaryFixed: "#001F27",
  primaryFixedDim: "#68D4F5",
  onPrimaryFixedVariant: "#004E5F",
  secondaryFixed: "#80BDB8",
  onSecondaryFixed: "#00251A",
  secondaryFixedDim: "#4DB6AC",
  onSecondaryFixedVariant: "#004D40",
  tertiaryFixed: "#FFF7D9",
  onTertiaryFixed: "#2A2000",
  tertiaryFixedDim: "#F2D878",
  onTertiaryFixedVariant: "#584A00",
  surfaceDim: "#0F1416",
  surfaceBright: "#353A3C",
  surfaceContainerLowest: "#0A0F11",
  surfaceContainerLow: "#171C1E",
  surfaceContainer: "#1B2022",
  surfaceContainerHigh: "#262B2D",
  surfaceContainerHighest: "#303638",
};

export const lightTheme = {
  ...MD3LightTheme,
  colors: lightColors,
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: darkColors,
};